-- Generated by ERDone (PostgreSQL)
-- 2026-06-29T20:47:58.219Z

CREATE TABLE "site" (
  "site_id" UUID NOT NULL,
  CONSTRAINT "PK_site" PRIMARY KEY ("site_id")
);

CREATE TABLE "structure" (
  "structure_id" UUID NOT NULL,
  "site_id" UUID NOT NULL,
  CONSTRAINT "PK_structure" PRIMARY KEY ("structure_id")
);

-- Foreign key constraints
ALTER TABLE "structure" ADD CONSTRAINT "FK_structure_site_id" FOREIGN KEY ("site_id") REFERENCES "site" ("site_id");

-- Indexes
CREATE INDEX "IX_structure_site_id" ON "structure" ("site_id");
