-- Generated by ERDone (PostgreSQL)
-- 2026-06-29T21:05:12.508Z

CREATE TABLE "site" (
  "site_id" UUID NOT NULL,
  CONSTRAINT "PK_site" PRIMARY KEY ("site_id")
);

CREATE TABLE "structure" (
  "structure_id" UUID NOT NULL,
  "site_id" UUID NOT NULL,
  CONSTRAINT "PK_structure" PRIMARY KEY ("structure_id")
);

CREATE TABLE "lp_system" (
  "lp_system_id" UUID NOT NULL,
  "structure_id" UUID NOT NULL,
  CONSTRAINT "PK_lp_system" PRIMARY KEY ("lp_system_id")
);

CREATE TABLE "lp_partial" (
  "lp_partial_id" UUID NOT NULL,
  "lp_system_id" UUID NOT NULL,
  CONSTRAINT "PK_lp_partial" PRIMARY KEY ("lp_partial_id")
);

CREATE TABLE "scope_item" (
  "lp_partial_id" UUID NOT NULL,
  "structure_id" UUID NOT NULL,
  "scope_id" UUID NOT NULL,
  CONSTRAINT "PK_scope_item" PRIMARY KEY ("lp_partial_id", "structure_id", "scope_id")
);

CREATE TABLE "scope" (
  "scope_id" UUID NOT NULL,
  CONSTRAINT "PK_scope" PRIMARY KEY ("scope_id")
);

CREATE TABLE "proposal" (
  "proposal_id" UUID NOT NULL,
  CONSTRAINT "PK_proposal" PRIMARY KEY ("proposal_id")
);

CREATE TABLE "submittal" (
  "submittal_id" UUID NOT NULL,
  CONSTRAINT "PK_submittal" PRIMARY KEY ("submittal_id")
);

CREATE TABLE "work_order" (
  "work_order_id" UUID NOT NULL,
  CONSTRAINT "PK_work_order" PRIMARY KEY ("work_order_id")
);

CREATE TABLE "phase" (
  "phase_id" TEXT NOT NULL,
  "scope_id" UUID NOT NULL,
  "proposal_id" UUID NOT NULL,
  "submittal_id" UUID NOT NULL,
  "work_order_id" UUID NOT NULL,
  CONSTRAINT "PK_phase" PRIMARY KEY ("phase_id")
);

CREATE TABLE "cost_collection" (
  "scope_id" UUID NOT NULL,
  "structure_id" UUID NOT NULL,
  "lp_partial_id" UUID NOT NULL
);

-- Foreign key constraints
ALTER TABLE "structure" ADD CONSTRAINT "FK_structure_site_id" FOREIGN KEY ("site_id") REFERENCES "site" ("site_id");
ALTER TABLE "lp_system" ADD CONSTRAINT "FK_lp_system_structure_id" FOREIGN KEY ("structure_id") REFERENCES "structure" ("structure_id");
ALTER TABLE "lp_partial" ADD CONSTRAINT "FK_lp_partial_lp_system_id" FOREIGN KEY ("lp_system_id") REFERENCES "lp_system" ("lp_system_id");
ALTER TABLE "scope_item" ADD CONSTRAINT "FK_scope_item_lp_partial_id" FOREIGN KEY ("lp_partial_id") REFERENCES "lp_partial" ("lp_partial_id");
ALTER TABLE "scope_item" ADD CONSTRAINT "FK_scope_item_structure_id" FOREIGN KEY ("structure_id") REFERENCES "structure" ("structure_id");
ALTER TABLE "scope_item" ADD CONSTRAINT "FK_scope_item_scope_id" FOREIGN KEY ("scope_id") REFERENCES "scope" ("scope_id");
ALTER TABLE "phase" ADD CONSTRAINT "FK_phase_scope_id" FOREIGN KEY ("scope_id") REFERENCES "scope" ("scope_id");
ALTER TABLE "phase" ADD CONSTRAINT "FK_phase_proposal_id" FOREIGN KEY ("proposal_id") REFERENCES "proposal" ("proposal_id");
ALTER TABLE "phase" ADD CONSTRAINT "FK_phase_submittal_id" FOREIGN KEY ("submittal_id") REFERENCES "submittal" ("submittal_id");
ALTER TABLE "phase" ADD CONSTRAINT "FK_phase_work_order_id" FOREIGN KEY ("work_order_id") REFERENCES "work_order" ("work_order_id");
ALTER TABLE "cost_collection" ADD CONSTRAINT "FK_cost_collection_scope_id" FOREIGN KEY ("scope_id") REFERENCES "scope_item" ("scope_id");
ALTER TABLE "cost_collection" ADD CONSTRAINT "FK_cost_collection_structure_id" FOREIGN KEY ("structure_id") REFERENCES "scope_item" ("structure_id");
ALTER TABLE "cost_collection" ADD CONSTRAINT "FK_cost_collection_lp_partial_id" FOREIGN KEY ("lp_partial_id") REFERENCES "scope_item" ("lp_partial_id");

-- Indexes
CREATE INDEX "IX_structure_site_id" ON "structure" ("site_id");
CREATE INDEX "IX_lp_system_structure_id" ON "lp_system" ("structure_id");
CREATE INDEX "IX_lp_partial_lp_system_id" ON "lp_partial" ("lp_system_id");
CREATE INDEX "IX_scope_item_lp_partial_id" ON "scope_item" ("lp_partial_id");
CREATE INDEX "IX_scope_item_structure_id" ON "scope_item" ("structure_id");
CREATE INDEX "IX_scope_item_scope_id" ON "scope_item" ("scope_id");
CREATE INDEX "IX_phase_scope_id" ON "phase" ("scope_id");
CREATE INDEX "IX_phase_proposal_id" ON "phase" ("proposal_id");
CREATE INDEX "IX_phase_submittal_id" ON "phase" ("submittal_id");
CREATE INDEX "IX_phase_work_order_id" ON "phase" ("work_order_id");
CREATE INDEX "IX_cost_collection_scope_id" ON "cost_collection" ("scope_id");
CREATE INDEX "IX_cost_collection_structure_id" ON "cost_collection" ("structure_id");
CREATE INDEX "IX_cost_collection_lp_partial_id" ON "cost_collection" ("lp_partial_id");
