-- Generated by ERDone (PostgreSQL)
-- 2026-06-29T20:48:48.152Z

CREATE TABLE "site" (
  "site_id" UUID NOT NULL,
  CONSTRAINT "PK_site" PRIMARY KEY ("site_id")
);

CREATE TABLE "structure" (
  "structure_id" UUID NOT NULL,
  "site_id" UUID NOT NULL,
  CONSTRAINT "PK_structure" PRIMARY KEY ("structure_id")
);

CREATE TABLE "lp_system" (
  "lp_system_id" UUID NOT NULL,
  "structure_id" UUID NOT NULL
);

-- Foreign key constraints
ALTER TABLE "structure" ADD CONSTRAINT "FK_structure_site_id" FOREIGN KEY ("site_id") REFERENCES "site" ("site_id");
ALTER TABLE "lp_system" ADD CONSTRAINT "FK_lp_system_structure_id" FOREIGN KEY ("structure_id") REFERENCES "structure" ("structure_id");

-- Indexes
CREATE INDEX "IX_structure_site_id" ON "structure" ("site_id");
CREATE INDEX "IX_lp_system_structure_id" ON "lp_system" ("structure_id");
